inherit_from:
  - https://raw.githubusercontent.com/carbonfive/c5-conventions/master/rubocop/rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
AllCops:
  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'node_modules/**/*'
    - 'lib/templates/**/*'
    - 'db/schema.rb'
    - 'bin/*'
    - 'config/initializers/devise.rb'
    - 'vendor/**/*'
